#!/usr/bin/python3
import sys
import time


def fact(number):
    for i in range(2, int(number**0.5)+1):
        if number % i == 0:
            return (i, number//i)
    return None


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()

    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as file:
            lines = file.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()

    for line in lines:
        number = int(line.strip())
        factors = fact(number)
        if factors:
            print(f"{number}={factors[0]}*{factors[1]}")
